/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author mastermoy
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        UsersMenu = new javax.swing.JMenu();
        insertUsersMenu = new javax.swing.JMenuItem();
        DepartmentMenu = new javax.swing.JMenu();
        insertDeparmentMenu = new javax.swing.JMenuItem();
        getDepartmentsMenu = new javax.swing.JMenuItem();
        updateDepartmentsMenu = new javax.swing.JMenuItem();
        deleteDepartmentsMenu = new javax.swing.JMenuItem();
        AssignmentsMenu = new javax.swing.JMenu();
        insertAssignmentMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        EquipmentMenu = new javax.swing.JMenu();
        insertEquipmentMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        UsersMenu.setText("Users");

        insertUsersMenu.setText("Insert");
        insertUsersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertUsersMenuActionPerformed(evt);
            }
        });
        UsersMenu.add(insertUsersMenu);

        menuBar.add(UsersMenu);

        DepartmentMenu.setMnemonic('e');
        DepartmentMenu.setText("Departments");

        insertDeparmentMenu.setMnemonic('t');
        insertDeparmentMenu.setText("Insert");
        insertDeparmentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDeparmentMenuActionPerformed(evt);
            }
        });
        DepartmentMenu.add(insertDeparmentMenu);

        getDepartmentsMenu.setMnemonic('y');
        getDepartmentsMenu.setText("Display");
        DepartmentMenu.add(getDepartmentsMenu);

        updateDepartmentsMenu.setMnemonic('p');
        updateDepartmentsMenu.setText("Update");
        DepartmentMenu.add(updateDepartmentsMenu);

        deleteDepartmentsMenu.setMnemonic('d');
        deleteDepartmentsMenu.setText("Delete");
        DepartmentMenu.add(deleteDepartmentsMenu);

        menuBar.add(DepartmentMenu);

        AssignmentsMenu.setText("Assignments");

        insertAssignmentMenu.setText("Insert");
        insertAssignmentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAssignmentMenuActionPerformed(evt);
            }
        });
        AssignmentsMenu.add(insertAssignmentMenu);

        menuBar.add(AssignmentsMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        EquipmentMenu.setText("Equipo");

        insertEquipmentMenu.setText("Insert");
        insertEquipmentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertEquipmentMenuActionPerformed(evt);
            }
        });
        EquipmentMenu.add(insertEquipmentMenu);

        menuBar.add(EquipmentMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void insertDeparmentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDeparmentMenuActionPerformed
        DepartmentsForm dForm1 = new DepartmentsForm();
        this.desktopPane.add(dForm1);
        dForm1.show();
        
    }//GEN-LAST:event_insertDeparmentMenuActionPerformed

    private void insertUsersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertUsersMenuActionPerformed
        UsersForm uForm1 = new UsersForm();
        this.desktopPane.add(uForm1);
        uForm1.show();
    }//GEN-LAST:event_insertUsersMenuActionPerformed

    private void insertAssignmentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAssignmentMenuActionPerformed
        AssignmentsForm  aForm1 = new AssignmentsForm();
        this.desktopPane.add(aForm1);
        aForm1.show();
    }//GEN-LAST:event_insertAssignmentMenuActionPerformed

    private void insertEquipmentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertEquipmentMenuActionPerformed
            EquipmentForm eForm1 = new EquipmentForm();
            this.desktopPane.add(eForm1);
            eForm1.show();
    }//GEN-LAST:event_insertEquipmentMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AssignmentsMenu;
    private javax.swing.JMenu DepartmentMenu;
    private javax.swing.JMenu EquipmentMenu;
    private javax.swing.JMenu UsersMenu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem deleteDepartmentsMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem getDepartmentsMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem insertAssignmentMenu;
    private javax.swing.JMenuItem insertDeparmentMenu;
    private javax.swing.JMenuItem insertEquipmentMenu;
    private javax.swing.JMenuItem insertUsersMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem updateDepartmentsMenu;
    // End of variables declaration//GEN-END:variables

}
